apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: argo-events-eventbus-policy
  namespace: argo-events
spec:
  podSelector:
    matchLabels:
      app: eventbus
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from: 
      - ipBlock:
          cidr: 0.0.0.0/0
      ports:
        - protocol: TCP
          port: 4222
        - protocol: TCP
          port: 6222
        - protocol: TCP
          port: 8222
  egress:
    - to:
      - ipBlock:
          cidr: 0.0.0.0/0
      ports:
        - protocol: TCP
          port: 4222
        - protocol: TCP
          port: 6222
        - protocol: TCP
          port: 8222
